-- AlterTable
ALTER TABLE "User" ADD COLUMN     "dailyQuota" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN     "lastActive" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "visibilityScore" DOUBLE PRECISION NOT NULL DEFAULT 1.0;
